---
title: "Playing with git"
format: gfm
fig-format: svg
editor: visual
---

## Trying things

```{r}
#| label: load packages
#| include: false

library(tidyverse)

```

Let's make a graph.

```{r}
#| label: graphity graph graph

penguins |>
  select(bill_len, bill_dep, island) |>
  na.omit() |>
  ggplot() +
  aes(x = bill_len, y = bill_dep, color = island) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(
    x = "Bill length (mm)",
    y = "Bill depth (mm)"
  )

```

```{r}
#| label: a different graph

penguins |>
  select(flipper_len, bill_dep, island) |>
  na.omit() |>
  ggplot() +
  aes(x = flipper_len, y = bill_dep, color = island) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw() +
  labs(
    x = "Flipper length (mm)",
    y = "Bill depth (mm)"
  )
```

```{r}
#| label: table!

penguins |>
  group_by(island) |>
  summarize(
          mean_bill_len = mean(bill_len),
          mean_bill_depth = mean(bill_dep)
          )

```
